version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  backend-tests:
    docker:
      - image: cimg/base:stable

    working_directory: ~/backend

    steps:
      - checkout
      - run:
          name: "run gradle tests"
          command: "./gradlew junitTests"
  frontend-tests:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - node/install:
          node-version: "16.16"
      - node/install-packages:
          app-dir: "./frontend"
      - run: 
          name: "Run frontend tests"
          command: "npm test"
          working_directory: "./frontend"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  backend-workflow:
    jobs:
      - backend-tests
  frontend-workflow:
    jobs:
      - frontend-tests
