version: 2.1

orbs:
  node: circleci/node@5.1.0
  gradle: circleci/gradle@3.0.0

jobs:
  backend-tests:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: chmod permissions
          working_directory: ./backend
          command: chmod +x ./gradlew
      - run:
          name: run gradle tests
          working_directory: ./backend
          command: ./gradlew junitTests

  frontend-tests:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - node/install:
          node-version: "16.16"
      - node/install-packages:
          app-dir: "./frontend"
      - run: 
          name: "Run frontend tests"
          command: "npm test"
          working_directory: "./frontend"

workflows:
  backend-workflow:
    jobs:
      - backend-tests
  frontend-workflow:
    jobs:
      - frontend-tests
